# -*- coding: utf-8 -*-
"""Clinical Note Generation Side by Side

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXawKUkV8UiMHDKItZMjzyDzv_awnU0n
"""

prompt_header = """
**Role:** You are an AI assistant specialized in generating clinical SOAP notes.

**Task:** Generate a concise, accurate, and clinically relevant SOAP note based **STRICTLY AND SOLELY** on the provided doctor-patient interaction transcript.

**CRITICAL INSTRUCTIONS:**

1.  **Strict Transcript Adherence:** Generate the SOAP note using **ONLY** information **explicitly stated** within the provided transcript.
2.  **NO Assumptions or External Knowledge:** **DO NOT** infer information, add details not mentioned (even if clinically likely), make assumptions, or use external medical knowledge. Adherence to the transcript is paramount.
3.  **Standard SOAP Structure:** Organize the output clearly into the following sections using **EXACTLY** these headings:
    *   **S – Subjective**
    *   **O – Objective**
    *   **A – Assessment**
    *   **P – Plan**
4.  **NO Extraneous Text:** The output must contain **ONLY** the four section headings (S, O, A, P) and the corresponding content derived *directly* from the transcript. **DO NOT** include introductory sentences (e.g., "Here is the SOAP note:"), concluding remarks, disclaimers, notes about the generation process, metadata, or *any* other text before, between, or after the S/O/A/P sections.

**Formatting:**

*   Use clear headings for each SOAP section (as listed above).
*   Be concise but ensure all relevant details *from the transcript* are included under the correct heading.
*   Use standard medical abbreviations only if they are unambiguous and directly supported by the transcript's terminology.

**Input:** You will receive a doctor-patient transcript.

**Output:** Generate **ONLY** the structured SOAP note (S/O/A/P sections and content) based on the critical instructions above.
"""
transcript = """
Doctor: Hi Lisa, I'm Dr. Petros. How can I help you today?

Lisa: Hi doctor, I've had this migraine for hours and it's really frustrating me. I've taken Tylenol and my migraine meds but they aren't helping.

Doctor: How long have you been hurting?

Lisa: It's been about 10 hours now but it feels like forever. These usually only last a few hours. It started with my normal blurry vision and pain in my right eye. The pain just keeps getting worse.

Doctor: I'm sorry to hear that. I'm going to ask you some questions to get some more information. I'll try to keep this brief since I know you don't feel well. I see in your chart that you have had migraines previously. Does this occur often?

Lisa: About once a month, sometimes more.

Doctor: Okay, and you have a prescription that you take when the headache gets bad?

Lisa: Yes, except this one isn't getting any better with my medicine.

Doctor: Well that's no good. Do you know the name of the medication you're prescribed?

Lisa: Yes, it's called Imitrex.

Doctor: Do you use the pill or the injection?

Lisa: Pills. I have taken two doses so far but the medicine has barely helped.

Doctor: Do you have any triggers? Anything that you know brings on your migraines?

Lisa: Not really, except I usually get one just before my period, but those aren't as bad as the others. The ones I get at the other times, I don't know what causes them. They're usually worse.

Doctor: Alright, are you experiencing any other symptoms related to your migraine right now?

Lisa: Light and sound make it worse, and any movement makes it worse too. I felt a little nauseous but I haven't thrown up any.

Doctor: Let's dim the lights in here a little to try to make you more comfortable. Are all of those symptoms normal for your migraine as well?

Lisa: Thanks, that does help a little. And yeah, all of that is typical. Sometimes I do throw up when I have a migraine, but not always.

Doctor: Okay, is there anything else I should know? Has anything made it better at all?

Lisa: Being still and lying down in the dark has helped some. Quiet helps, but nothing makes it stop. The pain hasn't gone away, just gotten a little better, then worse again.

Doctor: Have you noticed any vision changes or any numbness or weakness in your arms or legs?

Lisa: My vision is a little blurry, but that's normal during these episodes. I usually see stars around lights and flashes behind my eyes when I close them. I haven't noticed any weakness though.

Doctor: It sounds like you typically have migraines with aura. That's the technical term for what you describe as stars and flashes. Have you had any loss of consciousness, chest pain, or shortness of breath?

Lisa: No, none of that.

Doctor: Okay, so other than the extended length of time, this is a typical migraine for you? No new symptoms?

Lisa: Yeah, pretty much.

Doctor: Have you ever had a migraine that did not respond to the Imitrex before?

Lisa: Yeah, this happens every so often. It's really annoying.

Doctor: Do you have another treatment that usually works for you?

Lisa: I don't know. I think it can be different every time.

Doctor: Okay, that's fine. We will figure out a solution. Do you mind if I do a quick physical exam?

Lisa: No, go ahead.

Doctor: Thank you. I'm going to listen to your heart and lungs. Just breathe normally. Lungs are clear bilaterally. Heart sounds are normal with no murmurs, rubs or gallops. Now can you look at me and follow my finger please with just your eyes?

Lisa: [complies]

Doctor: Okay, great. Now I'm sorry to do this, but I need to briefly check your eyes with the light. It's going to be a little unpleasant.

Lisa: It's okay, I understand.

Doctor: I am looking for your pupils' response to light. I just want to be sure I don't see any signs pointing to anything other than a migraine here, like a stroke or aneurysm. Good, pupils are equal, round, and react normally to light and accommodation. Now I'm going to press on your sinuses. You should feel a little pressure, but tell me if you feel any pain.

Lisa: Okay. No pain.

Doctor: Good. Let me check your neck for a moment. Okay, your lymph nodes are normal as well. Now open your mouth and stick your tongue out.

Lisa: [complies]

Doctor: Good, no deviation there. Now, have you ever had a CT or MRI since you started having these headaches?

Lisa: Yes, I had one about five years ago when they started happening more regularly. It was normal.

Doctor: Okay, that's good. Can you stand up for me? I will stand behind you in case you lose your balance. Close your eyes and hold your arms out to your sides. I'm just checking your inner ear and proprioception.

Lisa: [complies]

Doctor: Good, I don't see any problems. You can sit back down. Now I want you to put both your hands against mine and push them down.

Lisa: [complies]

Doctor: Good. Now do the same with your legs, try to push my hands up.

Lisa: [complies]

Doctor: Good, thank you. Your movement and strength are normal and symmetrical, so that's a good sign. You have a normal neuro exam. Alright Lisa, I don't see anything too concerning. It seems you have a migraine that is simply unresponsive to your normal medication. Let's see if we can help you with this headache. I'm going to put in some orders and I'll be back in a few minutes to talk with you again.

Lisa: Okay, sure. Thank you.

[Later]

Doctor: All right Lisa, I have a sample here of a newer type of triptan medication. You can chew it or let it dissolve in your mouth so it acts a little more quickly. I'd like to try it and see if it is any more effective than the Imitrex. I'm also going to put some low flow oxygen on you. There's evidence that some other types of headaches can mimic migraine symptoms and some of them respond to oxygen therapy.

Lisa: I'm okay with that. Anything that makes this better.

Doctor: Okay, I will turn the lights off and send the nurse in with the medication and oxygen. I'd like you to lie back and rest until we see if it helps. Do you have any questions for now?

Lisa: No, I don't. Thank you.

[Later]

Doctor: Hi Lisa, are you feeling any better?

Lisa: Actually, I am. I started to feel the pain fade about 15 minutes ago. It's down to a dull ache now.

Doctor: That's great. How's your vision now?

Lisa: Almost normal. Nausea completely gone.

Doctor: Wonderful!

Lisa: You have no idea.

Doctor: I'm glad you're feeling better. I will write you a prescription for the newer medication. It's called Rizatriptan. Your most up-to-date pharmacy is in our system, correct?

Lisa: Yes, it is.

Doctor: Good. So now that you can think a little better, let's talk about what might be causing these.

Lisa: Okay.

Doctor: Have you ever done a migraine diary?

Lisa: No, not really.

Doctor: I think it would be a really good idea. You can keep a calendar just for this on your phone or something like that. Whenever you have a migraine, write down everything you can remember about that day - what you ate or drank, where you were, how you slept, that kind of thing. Hopefully you will start to see a pattern in what sets them off. It might be a food allergy, stress, or lack of sleep. Many women have hormonal migraines. I know you said you have them monthly, but that the ones unrelated to your menstrual cycle are different?

Lisa: Yes, they are.

Doctor: So maybe concentrate on those. Migraines are much easier to prevent than to treat. If you can discover your triggers, there are some medications you could try as a preventative measure, but I hate to go there if you can figure out what causes them and just avoid those triggers. Some of the preventative medications have significant side effects. At your age, I would rather avoid them if possible.

Lisa: I totally agree. I will start keeping track of the headaches and try to find out what is causing them.

Doctor: Great. I suggest you follow up on that with your primary care physician. If you don't have one, I will be happy to help you, but your best option is for consistent follow-up with your own doctor. Does this all sound okay to you?

Lisa: Yes, that works for me. Thank you so much.

Doctor: You are very welcome. Do you have any other questions for me?

Lisa: No, I'm just ready to go back home.

Doctor: Sounds like a good plan. All right Lisa, take care and feel better.

SOAP NOTE:
    """
prompt = prompt_header + "\n\nTranscript: " + transcript

from transformers import AutoModelForCausalLM, AutoTokenizer

base_model_name = "Qwen/Qwen3-4B"

# load the tokenizer and the model
base_tokenizer = AutoTokenizer.from_pretrained(base_model_name)
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    torch_dtype="auto",
    device_map="auto"
)

novel_model_name = "ClinicianFOCUS/Clinician-Note-2.0a"

# load the tokenizer and the model
novel_tokenizer = AutoTokenizer.from_pretrained(novel_model_name)
novel_model = AutoModelForCausalLM.from_pretrained(
    novel_model_name,
    torch_dtype="auto",
    device_map="auto"
)

# prepare the model input
messages = [
    {"role": "user", "content": prompt}
]
base_text = base_tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
    enable_thinking=True # Switches between thinking and non-thinking modes. Default is True.
)
base_model_inputs = base_tokenizer([base_text], return_tensors="pt").to(base_model.device)

# conduct text completion
generated_ids = base_model.generate(
    **base_model_inputs,
    max_new_tokens=32768,
    temperature=0.3,
    top_p=0.9,
    top_k=20,
)
output_ids = generated_ids[0][len(base_model_inputs.input_ids[0]):].tolist()

# parsing thinking content
try:
    # rindex finding 151668 (</think>)
    index = len(output_ids) - output_ids[::-1].index(151668)
except ValueError:
    index = 0

thinking_content = base_tokenizer.decode(output_ids[:index], skip_special_tokens=True).strip("\n")
content = base_tokenizer.decode(output_ids[index:], skip_special_tokens=True).strip("\n")

print("Base SOAP Note Generator:\n\n")
print("thinking content:", thinking_content)
print("content:", content)

novel_text = novel_tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
    enable_thinking=True # Switches between thinking and non-thinking modes. Default is True.
)
model_inputs = novel_tokenizer([novel_text], return_tensors="pt").to(novel_model.device)

# conduct text completion
generated_ids = novel_model.generate(
    **model_inputs,
    max_new_tokens=32768,
    temperature=0.3,
    top_p=0.9,
    top_k=20,
)
novel_output_ids = generated_ids[0][len(model_inputs.input_ids[0]):].tolist()

# parsing thinking content
try:
    # rindex finding 151668 (</think>)
    index = len(novel_output_ids) - novel_output_ids[::-1].index(151668)
except ValueError:
    index = 0

thinking_content = novel_tokenizer.decode(novel_output_ids[:index], skip_special_tokens=True).strip("\n")
content = novel_tokenizer.decode(novel_output_ids[index:], skip_special_tokens=True).strip("\n")

print("Novel SOAP Note Generator:\n\n")
print("thinking content:", thinking_content)
print("content:", content)
print(f"\n\n\n Transcript: {transcript}")